### ISSUE TITLE
Bug: Timestamp cause crush in Preprocessing 

### ISSUE THREAD

**Issue by aPovidlo** [aimclub/FEDOT#1059]
As I understand correctly, if data frame is containing feature datetime64[ns], it cause next error:

```
Traceback (most recent call last):
  File "C:\Users\andre\Documents\GitHub\FEDOT\fedot\api\api_utils\assumptions\assumptions_handler.py", line 70, in fit_assumption_and_check_correctness
    pipeline.fit(data_train, n_jobs=eval_n_jobs)
  File "C:\Users\andre\Documents\GitHub\FEDOT\fedot\core\pipelines\pipeline.py", line 187, in fit
    copied_input_data = self._preprocess(input_data)
  File "C:\Users\andre\Documents\GitHub\FEDOT\fedot\core\pipelines\pipeline.py", line 139, in _preprocess
    copied_input_data = self.preprocessor.optional_prepare_for_fit(pipeline=self,
  File "C:\Users\andre\Documents\GitHub\FEDOT\fedot\preprocessing\preprocessing.py", line 140, in optional_prepare_for_fit
    self._prepare_optional(pipeline, data, DEFAULT_SOURCE_NAME)
  File "C:\Users\andre\Documents\GitHub\FEDOT\fedot\preprocessing\preprocessing.py", line 284, in _prepare_optional
    data = action_if_no_tag(data, source_name)
  File "C:\Users\andre\Documents\GitHub\FEDOT\fedot\preprocessing\preprocessing.py", line 416, in _apply_categorical_encoding
    output_data.predict = output_data.predict.astype(float)
TypeError: float() argument must be a string or a number, not 'Timestamp'
```

In my opinioin, it is required to transform such features into numeric or categorical features in other way to avoid this crush

**Comment by IIaKyJIuH** [comment]
I've managed to reproduce the error with [an artificial example](https://www.online-python.com/gEDoweLmQt).

So, I suppose, the problem is in the "DataFrame to numpy" conversion via `np.asarray(...)` or `.to_numpy()`.

Instead of converting DataFrame's date object, which is more likely to be stored as `pandas.Timestamp`, into numpy's datetime object, they preserve pandas' Timestamp dtype almost every time except situation when datetime is the only dtype in the DataFrame.

Seems to me now, it's not a bug with the pandas.
